/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Lozano Carvajal
 */
public class crearExamenVista extends javax.swing.JFrame {

    /**
     * Creates new form crearExamenVista
     */
    public crearExamenVista() {
        initComponents();
        this.setSize(new Dimension(800, 600));
        this.setMinimumSize(new Dimension(800, 600));
        setLocation(100,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensajeEtiqueta = new javax.swing.JLabel();
        nombreParcialEtiqueta = new javax.swing.JLabel();
        nombreParicalCampo = new javax.swing.JTextField();
        materia1 = new javax.swing.JLabel();
        materia2 = new javax.swing.JLabel();
        materia3 = new javax.swing.JLabel();
        materia4 = new javax.swing.JLabel();
        check1 = new javax.swing.JCheckBox();
        check2 = new javax.swing.JCheckBox();
        check3 = new javax.swing.JCheckBox();
        check4 = new javax.swing.JCheckBox();
        cantidadPreguntasEtiqueta = new javax.swing.JLabel();
        Spinner1 = new javax.swing.JSpinner();
        Spinner2 = new javax.swing.JSpinner();
        Spinner3 = new javax.swing.JSpinner();
        Spinner4 = new javax.swing.JSpinner();
        crearBoton = new javax.swing.JButton();
        homeBoton = new javax.swing.JButton();
        backBoton = new javax.swing.JButton();
        imagenFondoCrear = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensajeEtiqueta.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        mensajeEtiqueta.setText("Seleccione los temas:");
        getContentPane().add(mensajeEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        nombreParcialEtiqueta.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        nombreParcialEtiqueta.setText("Nombre del parcial:");
        getContentPane().add(nombreParcialEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        nombreParicalCampo.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 11)); // NOI18N
        getContentPane().add(nombreParicalCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 180, 30));

        materia1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        materia1.setText("Matemáticas");
        getContentPane().add(materia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, -1, -1));

        materia2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        materia2.setText("Historia");
        getContentPane().add(materia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        materia3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        materia3.setText("Física");
        getContentPane().add(materia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 50, -1));

        materia4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        materia4.setText("Biología");
        getContentPane().add(materia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        check1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 11)); // NOI18N
        getContentPane().add(check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        check2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 11)); // NOI18N
        getContentPane().add(check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        check3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 11)); // NOI18N
        getContentPane().add(check3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        check4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 11)); // NOI18N
        getContentPane().add(check4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        cantidadPreguntasEtiqueta.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        cantidadPreguntasEtiqueta.setText("Cant. Preguntas");
        getContentPane().add(cantidadPreguntasEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, -1));

        Spinner1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        getContentPane().add(Spinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 40, 20));

        Spinner2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        getContentPane().add(Spinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 40, 20));

        Spinner3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        getContentPane().add(Spinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 40, 20));

        Spinner4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        getContentPane().add(Spinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 40, 20));

        crearBoton.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        crearBoton.setText("Crear Examen");
        crearBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBotonActionPerformed(evt);
            }
        });
        getContentPane().add(crearBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        homeBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenHome.png"))); // NOI18N
        homeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBotonActionPerformed(evt);
            }
        });
        getContentPane().add(homeBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        backBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenBack.png"))); // NOI18N
        backBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBotonActionPerformed(evt);
            }
        });
        getContentPane().add(backBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        imagenFondoCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenCrearExamen.png"))); // NOI18N
        getContentPane().add(imagenFondoCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBotonActionPerformed
        // TODO add your handling code here:
        loginVista abrir = new loginVista();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBotonActionPerformed

    private void backBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBotonActionPerformed
        // TODO add your handling code here:
        profesorVista abrir = new profesorVista();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBotonActionPerformed

    private void crearBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBotonActionPerformed
        profesorVista abrir = new profesorVista();
        abrir.setVisible(true);
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Se agregó correctamente el examen", "¡Operación exitosa!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_crearBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearExamenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearExamenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearExamenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearExamenVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearExamenVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Spinner1;
    private javax.swing.JSpinner Spinner2;
    private javax.swing.JSpinner Spinner3;
    private javax.swing.JSpinner Spinner4;
    private javax.swing.JButton backBoton;
    private javax.swing.JLabel cantidadPreguntasEtiqueta;
    private javax.swing.JCheckBox check1;
    private javax.swing.JCheckBox check2;
    private javax.swing.JCheckBox check3;
    private javax.swing.JCheckBox check4;
    private javax.swing.JButton crearBoton;
    private javax.swing.JButton homeBoton;
    private javax.swing.JLabel imagenFondoCrear;
    private javax.swing.JLabel materia1;
    private javax.swing.JLabel materia2;
    private javax.swing.JLabel materia3;
    private javax.swing.JLabel materia4;
    private javax.swing.JLabel mensajeEtiqueta;
    private javax.swing.JLabel nombreParcialEtiqueta;
    private javax.swing.JTextField nombreParicalCampo;
    // End of variables declaration//GEN-END:variables
}
