/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Lozano Carvajal
 */
public class preguntaVista2 extends javax.swing.JFrame {

    /**
     * Creates new form preguntaVista2
     */
    public preguntaVista2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preguntaTexto = new javax.swing.JTextField();
        agregarBoton = new javax.swing.JButton();
        mensajeEtiqueta = new javax.swing.JLabel();
        respuesta1 = new javax.swing.JTextField();
        respuesta2 = new javax.swing.JTextField();
        respuesta3 = new javax.swing.JTextField();
        respuesta4 = new javax.swing.JTextField();
        texto1 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        imagenFondoPregunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(preguntaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 350, 110));

        agregarBoton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        agregarBoton.setText("Agregar");
        getContentPane().add(agregarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, -1, -1));

        mensajeEtiqueta.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        mensajeEtiqueta.setText("Agrega la pregunta:");
        getContentPane().add(mensajeEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        getContentPane().add(respuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 220, 40));
        getContentPane().add(respuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 220, 40));
        getContentPane().add(respuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 220, 40));
        getContentPane().add(respuesta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 220, 40));

        texto1.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        texto1.setText("Respuesta 1:");
        getContentPane().add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        texto2.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        texto2.setText("Respuesta 2:");
        getContentPane().add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        texto3.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        texto3.setText("Respuesta 3:");
        getContentPane().add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        texto4.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        texto4.setText("Respuesta 4:");
        getContentPane().add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        imagenFondoPregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenPregunta.png"))); // NOI18N
        getContentPane().add(imagenFondoPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(preguntaVista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(preguntaVista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(preguntaVista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(preguntaVista2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new preguntaVista2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBoton;
    private javax.swing.JLabel imagenFondoPregunta;
    private javax.swing.JLabel mensajeEtiqueta;
    private javax.swing.JTextField preguntaTexto;
    private javax.swing.JTextField respuesta1;
    private javax.swing.JTextField respuesta2;
    private javax.swing.JTextField respuesta3;
    private javax.swing.JTextField respuesta4;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    // End of variables declaration//GEN-END:variables
}
