/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Dimension;

/**
 *
 * @author Lozano Carvajal
 */
public class profesorVista extends javax.swing.JFrame {

    /**
     * Creates new form profesorVista
     */
    public profesorVista() {
        initComponents();
        this.setSize(new Dimension(800, 600));
        this.setMinimumSize(new Dimension(800, 600));
        setLocation(100,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenidoEtiqueta = new javax.swing.JLabel();
        mensajeEtiqueta = new javax.swing.JLabel();
        agregarBoton = new javax.swing.JButton();
        crearBoton = new javax.swing.JButton();
        homeBoton = new javax.swing.JButton();
        temaBoton = new javax.swing.JButton();
        imagenFondoProfesor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenidoEtiqueta.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 70)); // NOI18N
        bienvenidoEtiqueta.setText("¡Bienvenido Profesor!");
        getContentPane().add(bienvenidoEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        mensajeEtiqueta.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 48)); // NOI18N
        mensajeEtiqueta.setText("¿Qué desea hacer?");
        getContentPane().add(mensajeEtiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        agregarBoton.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        agregarBoton.setText("Agregar pregunta");
        agregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBotonActionPerformed(evt);
            }
        });
        getContentPane().add(agregarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 323, -1, 60));

        crearBoton.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        crearBoton.setText("Crear Examen");
        crearBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearBotonActionPerformed(evt);
            }
        });
        getContentPane().add(crearBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 323, 180, 60));

        homeBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenHome.png"))); // NOI18N
        homeBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBotonActionPerformed(evt);
            }
        });
        getContentPane().add(homeBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        temaBoton.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 36)); // NOI18N
        temaBoton.setText("Crear Tema");
        temaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaBotonActionPerformed(evt);
            }
        });
        getContentPane().add(temaBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        imagenFondoProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenProfesorVista.png"))); // NOI18N
        getContentPane().add(imagenFondoProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBotonActionPerformed
        // TODO add your handling code here:
        preguntaVista abrir = new preguntaVista();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agregarBotonActionPerformed

    private void crearBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearBotonActionPerformed
        // TODO add your handling code here:
        crearExamenVista abrir = new crearExamenVista();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_crearBotonActionPerformed

    private void homeBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBotonActionPerformed
        // TODO add your handling code here:
        loginVista abrir = new loginVista();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBotonActionPerformed

    private void temaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaBotonActionPerformed
        // TODO add your handling code here:
        temaVista abrir = new temaVista();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_temaBotonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profesorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profesorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profesorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profesorVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profesorVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBoton;
    private javax.swing.JLabel bienvenidoEtiqueta;
    private javax.swing.JButton crearBoton;
    private javax.swing.JButton homeBoton;
    private javax.swing.JLabel imagenFondoProfesor;
    private javax.swing.JLabel mensajeEtiqueta;
    private javax.swing.JButton temaBoton;
    // End of variables declaration//GEN-END:variables
}
